### ISSUE TITLE
状态模块下的模拟次数统计错误

### ISSUE THREAD

**Issue by xnkjj** [thx/rap2-dolores#101]
模拟次数统计，出现越来越少的异常。

![image](https://user-images.githubusercontent.com/16268065/71711092-59ee6d00-2e3a-11ea-877a-72b948ac7eb8.png)

![image](https://user-images.githubusercontent.com/16268065/71711097-5fe44e00-2e3a-11ea-8a77-c6a5142d3d54.png)

**Comment by Bosn** [comment]
https://github.com/thx/rap2-dolores/issues/74
