### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by Lysuwel** [thx/rap2-dolores#102]
目录：rap2-dolores/
命令：nmp run build
./src/components/home/OwnedRepositoriesCard.tsx
  Line 16:43:  Parsing error: Unexpected token. Did you mean `{'>'}` or `&gt;`?

报错详情
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle rap2-dolores@1.0.0~prebuild: rap2-dolores@1.0.0
6 info lifecycle rap2-dolores@1.0.0~build: rap2-dolores@1.0.0
7 verbose lifecycle rap2-dolores@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle rap2-dolores@1.0.0~build: PATH: /usr/local/node/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/rap2/rap2-dolores/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle rap2-dolores@1.0.0~build: CWD: /data/rap2/rap2-dolores
10 silly lifecycle rap2-dolores@1.0.0~build: Args: [ '-c',
10 silly lifecycle   'npm run lint && npm run build-css && react-scripts build' ]
11 silly lifecycle rap2-dolores@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle rap2-dolores@1.0.0~build: Failed to exec build script
13 verbose stack Error: rap2-dolores@1.0.0 build: `npm run lint && npm run build-css && react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid rap2-dolores@1.0.0
15 verbose cwd /data/rap2/rap2-dolores
16 verbose Linux 3.10.0-1127.el7.x86_64
17 verbose argv "/usr/local/node/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.9.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error rap2-dolores@1.0.0 build: `npm run lint && npm run build-css && react-scripts build`
22 error Exit status 1
23 error Failed at the rap2-dolores@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

node  v10.9.0
CentOS Linux release 7.8.2003 (Core)

**Comment by lyx383982759** [comment]
你的问题解决了嘛？我也遇到了相同的问题

**Comment by Lysuwel** [comment]
> 你的问题解决了嘛？我也遇到了相同的问题

没有。加了官方的钉钉群准备问一下

**Comment by ganl** [comment]
Fix https://github.com/ganl/rap2-dolores/commit/14ffc8d13f2a47c5ac00a73952cca252e66ce647

**Comment by Bosn** [comment]
https://github.com/thx/rap2-dolores/issues/74
