### ISSUE TITLE
使用npm run build报错

### ISSUE THREAD

**Issue by 244180** [thx/rap2-dolores#105]
./src/components/editor/MoveModuleForm.tsx
  Line 81:6:  React Hook useEffect has missing dependencies: 'dispatch' and 'repositories.length'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/components/editor/MoveInterfaceForm.tsx
  Line 83:6:  React Hook useEffect has missing dependencies: 'dispatch' and 'repositories.length'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/components/repository/RepositoryForm.tsx
  Line 91:6:  React Hook useEffect has a missing dependency: 'dispatch'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

**Comment by Bosn** [comment]
https://github.com/thx/rap2-dolores/issues/74
