### ISSUE TITLE
安装完成后，页面一直在加载，怎么回事呢

### ISSUE THREAD

**Issue by keven0706** [thx/rap2-dolores#16]

**Comment by gaoac** [comment]
@keven0706 api服务器没启动（rap2-delos）

**Comment by fly2leoo** [comment]
确保delos模块启动，而且dolores模块的 config/config.*.js 配置正确，否则会看到 http://***/account/info请求失败，登录页面加载不出来

**Comment by puyeyu** [comment]
f12打开控制台看看有没有报错
