### ISSUE TITLE
Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (59)

### ISSUE THREAD

**Issue by jasonx4131** [thx/rap2-dolores#2]
@执行以下命令时报错[root@VM_217_200_centos config]# npm run test

> rap2-dolores@1.0.0 test /usr/local/rap2-dolores
> npm run linter

> rap2-dolores@1.0.0 linter /usr/local/rap2-dolores
> standard --fix

[root@VM_217_200_centos config]# npm run dev

> rap2-dolores@1.0.0 dev /usr/local/rap2-dolores
> npm run start

> rap2-dolores@1.0.0 start /usr/local/rap2-dolores
> npm-run-all -p watch-css start-js

> rap2-dolores@1.0.0 watch-css /usr/local/rap2-dolores
> npm run build-css && node-sass src/ -o src/ --watch --recursive

> rap2-dolores@1.0.0 start-js /usr/local/rap2-dolores
> react-scripts start

> rap2-dolores@1.0.0 build-css /usr/local/rap2-dolores
> node-sass src/ -o src/

/usr/local/rap2-dolores/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.3
    at module.exports (/usr/local/rap2-dolores/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/usr/local/rap2-dolores/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/rap2-dolores/node_modules/node-sass/bin/node-sass:11:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 build-css: `node-sass src/ -o src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 build-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-01T05_56_55_022Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 watch-css: `npm run build-css && node-sass src/ -o src/ --watch --recursive`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 watch-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-01T05_56_55_043Z-debug.log
ERROR: "watch-css" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 start: `npm-run-all -p watch-css start-js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-01T05_56_55_091Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 dev: `npm run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-01T05_56_55_111Z-debug.log

**Comment by webkong** [comment]
我也遇到了这个问题， 你可以单独安装 `node-sass` ， 如果还是不行，可以先安装 `node-gyp`

```
npm i node-sass
npm install -g node-gyp
```

**Comment by SuperAL** [comment]
用 `cnpm` 安装 `node-sass` 包，再不行的话安装一个指定版本的 `node-sass`，例如 `4.7.2`
