### ISSUE TITLE
rap2 能不能模拟固定的数据

### ISSUE THREAD

**Issue by liubin-5288** [thx/rap2-dolores#20]
当我导入json 数据后，我的列表数据被替换为相同的了，难道不能使用我写好 json 测试数据？![](https://i.imgur.com/bVYKTGF.png)

**Comment by alvarto** [comment]
可在初始值字段处填入这一小段JSON。

目前rap2和之前提供的$list功能并不完全重合，相关需求排期中，在此前麻烦使用上面这个workaround吧。

**Comment by lucaswangdev** [comment]
“可在navContent的初始值处填入这一小段JSON”，这一小段JSON是哪个，可以具体一点吗？

**Comment by alvarto** [comment]
![17_49_38__07_15_2018](https://user-images.githubusercontent.com/1797855/42732625-7f0e9158-8857-11e8-8c8b-85b39391e3e0.jpg)

**Comment by Bosn** [comment]
请参考mock.js或在mock.js中提问。

rap2会将接口文档编译成Mock.js规则，规则如何到数据，完全由mock.js操控。rap2不会干预。
