### ISSUE TITLE
docker容器内部署delos模块在经过nginx反向代理后无法匹配接口

### ISSUE THREAD

**Issue by fly2leoo** [thx/rap2-dolores#23]
dolores模块页面访问正常，可以成功注册、登录，并可以进行接口新增和修改，但是请求接口时却无法匹配接口

请求例示 http://rest.mock.domain.com/app/mock/16/GET/example/1520095481062
返回结果如下
{
"isOk": false,
"errMsg": "未匹配到任何接口 No matched interface"
}

Docker容器使用官方镜像创建docker.io/node，映射内部8080端口
docker run -it -d -p 39999:8080  993f38da6c6c
直接使用node启动模块
docker exec -d 9603945a7fcd node /home/node/rap2-delos/dist/dispatch.js

反向代理匹配如下
server {
        listen  80;
        server_name rest.mock.domain.com;
        location / {
                proxy_pass  http://127.0.0.1:39999;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}

dolores模块使用nginx单独部署
server {
        listen  80;
        server_name rap2.domain.com;
        location / {
                root    /var/www/html/rap2;
                index   index.html;
        }
}

**Comment by fly2leoo** [comment]
本地部署也有同样的问题，例如以下请求
http://127.0.0.1:8080/app/mock/16/GET/example/1520095481062
得到结果{
"isOk": false,
"errMsg": "未匹配到任何接口 No matched interface"
}

**Comment by fly2leoo** [comment]
好吧... 问题已解决

dolores模块，src/component/editor/InterfaceSummary.jsx
Line 42: <Link to={`${serve}/app/mock/${repository.id}/${itf.method}/${itf.url}`} target='_blank'>{itf.url}</Link>

把变量${itf.method}/ 删除掉，然后重新编译

**Comment by alvarto** [comment]
问题的核心在于 rap2 为了支持 restful 的接口设计，会在mock时加入method，但在某个更新之后引入了bug导致method匹配不上了。

**Comment by lokikyou** [comment]
补充一下，测试按钮需要改rap2-delos中的文件
public/libs/jquery.rap.js 
将41行中的${match.method}给去掉

**Comment by Bosn** [comment]
fixed
