### ISSUE TITLE
非官方rap2-dolores部署文档

### ISSUE THREAD

**Issue by BladeCode** [thx/rap2-dolores#24]
* [构建项目](#%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE)
    * [安装基本工具](#%E5%AE%89%E8%A3%85%E5%9F%BA%E6%9C%AC%E5%B7%A5%E5%85%B7)
    * [获取源代码](#%E8%8E%B7%E5%8F%96%E6%BA%90%E4%BB%A3%E7%A0%81)
    * [导入VS Code](#%E5%AF%BC%E5%85%A5VS%20Code)
* [环境配置](#%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)
    * [配置文件](#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)
* [启动项目](#%E5%90%AF%E5%8A%A8%E9%A1%B9%E7%9B%AE)
    * [安装项目依赖包](#%E5%AE%89%E8%A3%85%E9%A1%B9%E7%9B%AE%E4%BE%9D%E8%B5%96%E5%8C%85)
    * [编译启动项目](#%E7%BC%96%E8%AF%91%E5%90%AF%E5%8A%A8%E9%A1%B9%E7%9B%AE)
* [常见问题](#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    * [部署问题](#%E9%83%A8%E7%BD%B2%E9%97%AE%E9%A2%98)
    * [如何获取更新](#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E6%9B%B4%E6%96%B0)

## 前言
RAP2 包含两个组件 **客户端：**[rap2-dolores](https://github.com/thx/rap2-dolores) 和 **服务端：**[rap2-delos](https://github.com/thx/rap2-delos)  
部署RAP2需要亲具有Node+Linux+MySQL的运维知识，如果亲对此不是很了解，建议用http://rap2.taobao.org 线上版本就可以了。

注意：
该项目的部署是建立在[rap2-delos](https://github.com/thx/rap2-delos)上，因此，需要先部署[rap2-delos](https://github.com/thx/rap2-delos)项目

### 安装基本工具
* [Git](https://git-scm.com/downloads)
* [Node 8.9.4+](https://nodejs.org/zh-cn/download)
* [VS Code](https://code.visualstudio.com/download)(非必需)

以上基本工具请根据自身需要，下载对应系统安装包，请自行解决安装配置等问题，这里不做过多说明

### 获取源代码
``` sh
git clone https://github.com/thx/rap2-dolores.git
```

### 导入VS Code
这里的开发编辑工具推荐，当然你也可以用自己熟悉的开发工具

### 配置文件

目录：rap2-dolores/src/config  
文件：`config.dev.ts`;其中dev，表示开发环境，其他同理  
修改：`config.dev.ts`文件，`serve`地址是**服务端**[rap2-delos]()部署成功后的地址，默认：`'http://localhost:8080'`

### 安装项目依赖包

项目根目录下执行

```sh
npm install
```

> 如果下载缓慢，请使用[淘宝npm镜像](https://npm.taobao.org)

### 编译启动项目

* 开发模式  
自动监视改变后重新编译
    ```sh
    npm run dev
    ```
    备注：测试用例
    ```sh
    npm run test
    ```
* 生产模式  
编译React生产包
    ```sh
    npm run build
    ```
    用serve命令或nginx服务器路由到编译产出的build文件夹作为静态服务器即可
    ```sh
    serve -s ./build -p 80
    ```

看到浏览器中出现登录页面，表示部署成功

### 部署问题
1. 执行`npm run dev`，提示
    ```sh
    return process.dlopen(module,path._makeLong(filename))
    ...
    ...node_modules\node-sass\vendor\win32-x64-57\binding.node is not a valid Win32 application...
    ```

    原因：项目依赖包`node-sass`没有安装完全  
    解决方法：`npm install node-sass`

2. 项目运行起来，但一直停留在加载动画那里
    
    浏览器控制台输出：  
    `GET http://127.0.0.1:8080/account/info  ==>>
    Failed to load http://127.0.0.1:8080/account/info`

    原因：未修改`rap2-delos/src/config`目录下服务端连接地址,或者修改结果与[rap2-dolores](https://github.com/thx/rap2-dolores)实际提供服务地址不匹配
    解决方法：修改`config.dev.ts`文件serve配置信息
    >如果Windows系统修改正确无误后，依旧出错，那么查看hosts(路径：C:\Windows\System32\drivers\etc)中127.0.0.1的IP前是否有`#`，如果有请取消注释

### 如何获取更新
目前请选择`master`分支源码，后续其他分支请看相应分支说明文档。在开发环境中git pull来获取最新的源码更新，每一期更新都会有对应的update.md请关注并按照上面的指示进行升级工作。

更详细的安装部署请移步：[https://incoder.org/2018/03/27/rap2](https://incoder.org/2018/03/27/rap2)

**Comment by lijiangwei** [comment]
部署到本地，为什么每次登录都需要数据验证码，这个是在哪配置的吗？
