### ISSUE TITLE
RAP2如何导出pdf或者word文档？

### ISSUE THREAD

**Issue by meathross** [thx/rap2-dolores#27]
像Rap1一样
![image](https://user-images.githubusercontent.com/14865604/38180673-f4a3bc98-3660-11e8-97b8-a479fdce55d6.png)

**Comment by Var-iazioni** [comment]
我也没找到这个功能。。应该还没开发。。。。

**Comment by AnInputForce** [comment]
这个确实很需要，有大神能指导一二有办法变通实现么？

**Comment by meathross** [comment]
如果现在维护的接口还不多，可以考虑使用。http://yapi.demo.qunar.com/

**Comment by Bosn** [comment]
暂不提供
