### ISSUE TITLE
rap2是否能添加“页面”的功能？

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-dolores#28]
rap1的关系是 仓库——模块——页面——接口
rap2的关系是 仓库——模块——接口
rap2缺少了页面的功能，如果一个模块的接口很多的话，看起来很不清晰。建议在接口上层新增“页面”，作为树形结构展示

**Comment by Bosn** [comment]
RAP2作者简化了这一层级。。。似乎没有移回去的打算。请善用搜索。。。。
