### ISSUE TITLE
账号登出问题

### ISSUE THREAD

**Issue by mrcuijt** [thx/rap2-dolores#29]
账号的登出功能没有完成吗，我这边点击登出后账号并没有登出，只是响应的页面返回到了登录页面，我再点击头部菜单的时候就直接登上了我的账号。
![004](https://user-images.githubusercontent.com/18755157/38465955-747ed234-3b54-11e8-861a-5ca5c25a0a46.png)
![002](https://user-images.githubusercontent.com/18755157/38465960-83074f8e-3b54-11e8-8a32-68fa2b88108d.png)
![003](https://user-images.githubusercontent.com/18755157/38465962-85f23ec0-3b54-11e8-91ab-63e54492e0e5.png)

**Comment by Bosn** [comment]
您再试试，最新代码应该已解决
