### ISSUE TITLE
dev/prod 皆运行成功，首页无法成功加载

### ISSUE THREAD

**Issue by printfcoder** [thx/rap2-dolores#3]
## 使用node v9.2.0，npm v5.5.1

1. dev 模式运行

![image](https://user-images.githubusercontent.com/20906540/33473845-09655eb0-d6b3-11e7-87b6-e6f072a00250.png)

2. 其它机器远程访问3000端口 

![image](https://user-images.githubusercontent.com/20906540/33473832-f9b03a6c-d6b2-11e7-9745-c357db3110fb.png)

3. 尝试过使用发布模式运行，配置文件如下：
`module.exports = {
  serve: 'http://127.0.0.1:8080',
  keys: ['some secret hurr'],
  session: {
    key: 'koa:sess'
  }
}`

错误依旧：

![image](https://user-images.githubusercontent.com/20906540/33474278-e0dd077a-d6b4-11e7-855a-07752e7ce8c1.png)

而使用serve 为 http://rap2api.taobao.org时，可以使用，而http://127.0.0.1:8080是通的，不解。

delos已经启动，与dolores在一台服务器：
![image](https://user-images.githubusercontent.com/20906540/33474379-51598348-d6b5-11e7-8d40-9069dbe03815.png)
访问效果：
![image](https://user-images.githubusercontent.com/20906540/33474420-76d02186-d6b5-11e7-95b2-7588f5183e00.png)

**Comment by printfcoder** [comment]
已解决，理解错误了，config.prod.js的serve只是用来调数据的restful API根地址。

**Comment by gzliudan** [comment]
请问要怎样配置？
