### ISSUE TITLE
Unexpected token I in JSON at position 0.

### ISSUE THREAD

**Issue by 283775789** [thx/rap2-dolores#32]
本地部署时，注册不了用户，在注册的时候出现这个错误：
Unexpected token I in JSON at position 0.

**Comment by sitcode** [comment]
数据库表有的大写有的小写注意一下，有bug

**Comment by Var-iazioni** [comment]
我也遇到这个问题了。。。难道需要重新建一遍库？

**Comment by wxxcarl** [comment]
什么意思？？就这样关了？到底怎么解决？

**Comment by Bosn** [comment]
@wxxcarl 2楼回复了啊，数据库大小写问题，是数据库case sensitive配置。

另外本身后端错误，具体什么错误，需要去排查一下。没有详细的server错误日志，很难了解真实的出错原因。

**Comment by wxxcarl** [comment]
> @wxxcarl 2楼回复了啊，数据库大小写问题，是数据库case sensitive配置。
> 
> 另外本身后端错误，具体什么错误，需要去排查一下。没有详细的server错误日志，很难了解真实的出错原因。

那这个严重bug半年了没修复，根本没法跑，本地部署的功能就这样放弃了吗？或者计划什么时候修复？

**Comment by wxxcarl** [comment]
已解决，数据库版本问题

**Comment by afresh** [comment]
> 已解决，数据库版本问题

哪个版本好用啊？

**Comment by wxxcarl** [comment]
> > 已解决，数据库版本问题
> 
> 哪个版本好用啊？

Server version: 8.0.13 MySQL Community Server - GPL

**Comment by afresh** [comment]
> > > 已解决，数据库版本问题
> > 
> > 
> > 哪个版本好用啊？
> 
> Server version: 8.0.13 MySQL Community Server - GPL

我这边好像不是数据库的问题，因为我服务用dev版本是可以的。
