### ISSUE TITLE
nodejs 8.11.1部署失败

### ISSUE THREAD

**Issue by Var-iazioni** [thx/rap2-dolores#33]
npm install之后会无限重复以下内容：
=========================================
gyp verb install input version string "8.11.1"
gyp verb install installing version: 8.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.11.1
gyp verb ensuring nodedir is created /home/rap2-dolores/node_modules/node-sass/.node-gyp/8.11.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/rap2-dolores/node_modules/node-sass/.node-gyp/8.11.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/rap2-dolores/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.11.1' ]

ctrl+C强制结束后，重新npm install成功，但是npm run build报错如下：
=========================================
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/rap2-dolores/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/rap2-dolores/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/rap2-dolores/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/rap2-dolores/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/rap2-dolores/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/rap2-dolores/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/rap2-dolores/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 build-css: `node-sass src/ -o src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 build-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-16T10_03_51_851Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 build: `npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-16T10_03_51_864Z-debug.log

相同环境，rap2-delos可以部署成功
=========================================

**Comment by Bosn** [comment]
node版本更新下？

**Comment by Var-iazioni** [comment]
是sass安装时权限的问题，命令改成npm install --unsafe-perm就可以了。。
