### ISSUE TITLE
新建仓库后点击仓库显示404？serve运行的，有人遇到么？

### ISSUE THREAD

**Issue by Var-iazioni** [thx/rap2-dolores#34]
其他功能貌似没什么问题。测试数据只能去库里删除么。。

**Comment by sczhaoqi** [comment]
同
/repository/get?id=16 请求返回
{isOk: false, errMsg: "对不起，您没有访问该数据的权限。 Sorry, you have no access to visit this data."}
errMsg
:
"对不起，您没有访问该数据的权限。 Sorry, you have no access to visit this data."
isOk
:
false}

**Comment by zhanngle** [comment]
我也刚刚遇到了这个错,什么情况啊

**Comment by akrick** [comment]
好大一个404

**Comment by akrick** [comment]
今天早上还可以访问，下午突然不行了

**Comment by Bosn** [comment]
因为刚把在做服务器版本升级哈，现在应该恢复正常啦再试试

**Comment by brucejiao** [comment]
http://localhost:5000/repository/editor?id=17    页面状态404,请问下这是什么情况？？

**Comment by Bosn** [comment]
@brucejiao 更新到最新的代码哈，然后tsc重新编译下，然后重启下就可以了。

**Comment by sczhaoqi** [comment]
问题没有解决吧!
我仔细研究后发现是因为没有给新建的仓库设定organizationId 所以导致查询时 后端返回了无权限
前端显示为404
所以问题是创建仓库的前端代码中没有设定organizationId,还是新建的用户没有organizationId 这种情况没有考虑到,后端没有设定接口提供默认值/为空时的处理逻辑不严谨,还要仔细研究
@Bosn

**Comment by Bosn** [comment]
@sczhaoqi 确实……我也发现了新创建仓库竟然不带orgId...，我也是接手的rap2很多坑，明天会修复哦

**Comment by Bosn** [comment]
临时办法：创建仓库，在团队里创建别在主页创建，明天我加一个团队选择，把全部没团队的项目归到项目数最多的团队。

**Comment by Var-iazioni** [comment]
期待修复。。。

**Comment by Bosn** [comment]
@Var-iazioni 已经修复了，更新代码试一下。下面为修复日志，了解一下：

https://github.com/thx/rap2-delos/commit/48eacfebfce2b15df715317827e0515b2f589895
