### ISSUE TITLE
我想问下，部署RAP2是不是只能在Linux或Mac系统上

### ISSUE THREAD

**Issue by zhiqiangchung** [thx/rap2-dolores#35]
我用的是Windows操作系统，按步骤执行npm -install就报错，报错原因看似不支持此平台，我记得RAP能在Windows部署，RAP2却不能吗？

**Comment by Bosn** [comment]
可以部署，不过最近引入了一个md5is包不支持windows，明天会修复

**Comment by Bosn** [comment]
已经修复，可以拉一下代码试一下哈。之前是一个不再使用的md5is包不支持跨平台，已经删掉了这个包。
