### ISSUE TITLE
RAP2功能建议

### ISSUE THREAD

**Issue by zhiqiangchung** [thx/rap2-dolores#36]
我在使用RAP2功能的时候，确实感觉比原RAP好用不少。但也遇到了一些功能上的问题，

1.接口字段能否新增一列，标识该字段是否为必输字段；
2.数据类型能否增加数据长度限制的标注，如String(100)这种，表示最多只能输入100个字符长度的字符串；
3.现在生产的Mock数据都是Jason格式的，是否能够生成XML格式的？
4.修订日志目前只能定位到修改了哪个接口，是否能够精确定位到修改了具体的哪些内容？

目前就遇到以上问题，如果可以的话，我希望能够为RAP的功能开发出一份力。
祝，越做越好！
谢谢！

**Comment by Bosn** [comment]
感谢您的意见和反馈

0. RAP1是我们组其他同学重构的，目前也是一直在维护的项目，但是是新项目，RAP1做了很多年，很多细节功能还在逐步迁移过来。
1. 提过，计划中
2. Mock规则我们使用的是Mock.js第三方，长度限制和逻辑判断属于自动化测试的范畴，我们内部有小组在调研和开发，但是还没有到可以放出来开源的程度。有进展我会告诉大家。
3. json => xml自己用一个软件转换一下吧，并不会非常困难。RAP暂时没有人力做这种功能哦。
4. 版本比对也提过了，在日程中。
