### ISSUE TITLE
一直报这个错误，已经卸载安装多次，求解答

### ISSUE THREAD

**Issue by brucejiao** [thx/rap2-dolores#37]
Error: Cannot find module 'D:\rap2-delos\rap2-dolores\node_modules\node-sass\bin\node-sass'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3

**Comment by Bosn** [comment]
npm install成功了嘛？

**Comment by brucejiao** [comment]
npm install 成功了
![image](https://user-images.githubusercontent.com/17822149/38975166-6c6ce778-43df-11e8-975b-b2b8d960591a.png)

**Comment by Bosn** [comment]
google了下，你可以试试删除package.json.lock文件，然后删掉node_modules后重新install

```bash
rm -f package.json.lock
rm -rf node_modules
npm install
```

**Comment by brucejiao** [comment]
多谢，现在已经可以跑起来了。我想再问一下怎样可以把http://rap2.taobao.org/的数据迁移到本地数据库

**Comment by Bosn** [comment]
正在做导入导出，项目级的。不过只能一个项目一个项目导，并且只能导自己有权限的项目（废话啦）

**Comment by brucejiao** [comment]
嗯嗯，好的多谢。加油！！！
