### ISSUE TITLE
npm install报错

### ISSUE THREAD

**Issue by MR820** [thx/rap2-dolores#38]
Binary has a problem: Error: \\?\E:\rap2\rap2-dolores\node_modules\node-sass\vendor\win32-x64-57\binding.node is not a valid Win32 application.
\\?\E:\rap2\rap2-dolores\node_modules\node-sass\vendor\win32-x64-57\binding.node

**Comment by Bosn** [comment]
node安装错误，本区不负责node安装技术指导，谢谢。

**Comment by MR820** [comment]
rm -rf package-lock.json
rm -rf node_modules
npm install
网络不稳定，多是几次就成功了

**Comment by MR820** [comment]
建议在git命令行窗口中运行npm install
