### ISSUE TITLE
执行 npm run dev 时出现编辑错误

### ISSUE THREAD

**Issue by hqwlkj** [thx/rap2-dolores#39]
从git上clone下来代码，执行npm run dev 出现下面错误，

![image](https://user-images.githubusercontent.com/12181423/39037418-05071138-44b3-11e8-9062-fa0317d3db29.png)

**Comment by Bosn** [comment]
确认版本，确认有npm install

**Comment by hqwlkj** [comment]
@Bosn  我执行了 npm install 然后执行的 npm run dev;

![image](https://user-images.githubusercontent.com/12181423/39041015-b84b54d2-44ba-11e8-9b1e-2ef57c17fa76.png)


没有修改任何配置

**Comment by hqwlkj** [comment]
只有是 .jsx  为后缀的文件都编译不过

**Comment by Bosn** [comment]
加钉钉群，首页README有群号
