### ISSUE TITLE
serve -s ./build -p 80报错

### ISSUE THREAD

**Issue by MR820** [thx/rap2-dolores#40]
测试环境以跑通

生产环境下
serve -s ./build -p 80
bash: serve: command not found

**Comment by hqwlkj** [comment]
@MR820   请问一下 你们clone 了代码之后有没有修改什么配置，我这边 .jsx 文件编译不过。你们是怎么处理的  ?    #39

**Comment by MR820** [comment]
没有改.jsx的相关东东，直接npm run build就过了

**Comment by hqwlkj** [comment]
郁闷 ，我下载了，就报错

**Comment by gxxc** [comment]
npm install serve
