### ISSUE TITLE
无法导入JSON, 提示 Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by gbKidCoding** [thx/rap2-dolores#46]
JSON 如下

{
    "code": "0",
    "result": {
        "data": [
            {
                "businessTypes": null,
                "children": [],
                "code": "10001",
                "createDeptId": 0,
                "createDeptName": "",
                "createTime": 0,
                "creatorId": 0,
                "creatorName": "",
                "description": "",
                "district": "",
                "fullName": "测试部门",
                "id": 1,
                "level": 1,
                "name": "测试部门",
                "parent": null,
                "path": "abcd",
                "roles": [],
                "sortIndex": 1,
                "status": 1,
                "updateTime": 0,
                "updaterId": null,
                "updaterName": ""
            },
            {
                "businessTypes": null,
                "children": [],
                "code": "1000101",
                "createDeptId": 0,
                "createDeptName": "",
                "createTime": 0,
                "creatorId": 0,
                "creatorName": "",
                "description": "",
                "district": "",
                "fullName": "测试部门-2",
                "id": 2,
                "level": 2,
                "name": "测试部门-2",
                "parent": null,
                "path": "abcd-123",
                "roles": [],
                "sortIndex": 1,
                "status": 1,
                "updateTime": 0,
                "updaterId": null,
                "updaterName": ""
            },
            {
                "businessTypes": "BRANCH_OFFICE",
                "children": [],
                "code": "320204000000",
                "createDeptId": 2,
                "createDeptName": "",
                "createTime": 1525850865696,
                "creatorId": 3,
                "creatorName": "管理员",
                "description": "",
                "district": "1",
                "fullName": "大队",
                "id": 3,
                "level": 1,
                "name": "大队",
                "parent": null,
                "path": "nmu4",
                "roles": [],
                "sortIndex": 1,
                "status": 1,
                "updateTime": 1525850865696,
                "updaterId": 3,
                "updaterName": "管理员"
            }
        ],
        "pageNo": 0,
        "pageSize": 25,
        "total": 3,
        "totalPages": 1
    },
    "status": 200,
    "timestamp": 1525850935517
}

![image](https://user-images.githubusercontent.com/13358002/39801908-45115676-539f-11e8-8406-4d05b46fc511.png)

**Comment by shekobe** [comment]
这个项目是才开始搞的吗，这种错不应该吧 ，，

把  "businessTypes": null,   改成 "businessTypes": “”，就可以了，希望有人马上处理这个bug呀。

**Comment by gbKidCoding** [comment]
谢谢可以了
