### ISSUE TITLE
响应内容中的Function类型，执行时上下文为undefined

### ISSUE THREAD

**Issue by liguohao96** [thx/rap2-dolores#49]
根据https://github.com/nuysoft/Mock/wiki/Syntax-Specification中第6条所述，

6. 属性值是函数 Function
`'name': function`
执行函数 function，取其返回值作为最终的属性值，函数的上下文为属性 'name' 所在的对象。

然而执行时，this为undefined。

**Comment by Bosn** [comment]
RAP2负责生成mock模板，从mock模板到mock数据，完全由mock.js决定。绝大部分情况，rap2不会也不应该做特殊的处理。
