### ISSUE TITLE
mock接口url拼接错误

### ISSUE THREAD

**Issue by kkroy-zs** [thx/rap2-dolores#51]
定义地址为：`/api/user/login`
点击地址后，浏览器地址栏中的mock url为：`http://xxx.xxx.xxx.xxx:8080/app/mock/11//api/user/login`

mock url中，`http://xxx.xxx.xxx.xxx:8080/app/mock/11/`与 `/api/user/login`的拼接没有考虑路径分隔符重复的问题。

**Comment by Bosn** [comment]
已修复
