### ISSUE TITLE
 serve -s ./build -p 80 启动正常，也可以用，但是有个报错

### ISSUE THREAD

**Issue by hassan5134** [thx/rap2-dolores#52]
# serve -s ./build -p 80
    { Error: Command failed: xsel --clipboard --input
    xsel: Can't open display: (null)
    : Inappropriate ioctl for device

    at Promise.all.then.arr (/usr/local/node-v8.11.1-linux-x64/lib/node_modules/serve/node_modules/clipboardy/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
      code: 1,
      killed: false,
      stdout: '',
      stderr: 'xsel: Can\'t open display: (null)\n: Inappropriate ioctl for device\n',
      failed: true,
      signal: null,
      cmd: 'xsel --clipboard --input',
      timedOut: false }

**Comment by kkroy-zs** [comment]
这个是serve的问题。
详细在
serve的issue [#373](https://github.com/zeit/serve/issues/373)
中有记述
