### ISSUE TITLE
页面样式展示错乱

### ISSUE THREAD

**Issue by Haphets** [thx/rap2-dolores#59]
<img width="1434" alt="page" src="https://user-images.githubusercontent.com/19382744/41272511-04b5609a-6e48-11e8-8093-cc7216991191.png">

打开控制台报错如下:
<img width="1436" alt="console" src="https://user-images.githubusercontent.com/19382744/41272522-0e482f66-6e48-11e8-9d8e-d2e8e26f88da.png">

复制错误如下:
websocket.js:32 WebSocket connection to 'ws://rap2-dolore-自己的域名/sockjs-node/342/kfnokayq/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
WebSocketTransport @ websocket.js:32
iframe-bootstrap.js:73 Uncaught Error: Incompatible SockJS! Main site uses: "1.0.1", the iframe: "1.1.4".
    at a (iframe-bootstrap.js:73)
iframe-bootstrap.js:73 Uncaught Error: Incompatible SockJS! Main site uses: "1.0.1", the iframe: "1.1.4".
    at a (iframe-bootstrap.js:73)

**Comment by AnInputForce** [comment]
什么环境：
操作系统
浏览器
哪个版本
哪个分支
如何部署的
