### ISSUE TITLE
serve -s ./build 可以后台运行吗？

### ISSUE THREAD

**Issue by Haphets** [thx/rap2-dolores#60]
现在运行serve -s ./build 以后，ctrl+c就退出了，有什么方式可以后台启动运行

**Comment by AnInputForce** [comment]
不知道支不支持 nohub参数
也可以把.build 扔到nginx下，配置一个静态服务器，指向.build即可。

**Comment by gzliudan** [comment]
请问要怎样配置？

**Comment by Bosn** [comment]
本repo不提供运维技术支持。该issue和rap项目无关，closed。

后台运行可以参考nohup和pm2

**Comment by xiaobingchan** [comment]
serve -s ./build 就算你用了nohup 也不能保持后台启动的。。。。你应该 cd ./build && npm start 然后在用nginx设置 端口转发到3000端口就好 ` location / {  
         proxy_pass  http://localhost:8080/;
        }`
