### ISSUE TITLE
需求：输入类的控件Tab可以切换

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-dolores#61]
希望添加输入项使用Tab可以切换的功能，录入的效率会高一些。

![6154105a-bea4-4d5e-acc5-4583fbe180b8](https://user-images.githubusercontent.com/2356974/41332439-8a0cc544-6f10-11e8-940f-58a05a489fd8.png)

**Comment by Bosn** [comment]
收到

**Comment by Bosn** [comment]
统一整理到https://github.com/thx/rap2-delos/issues/247
