### ISSUE TITLE
需求：新增复制接口的功能

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-dolores#62]
有的接口很多参数相似，建议增加复制的功能，这样我们就可以复制一些相似的接口，修改接口的名称，地址，类型等，快速生成一个新的接口，然后进行一些修改。
或者，我们大多数的接口的响应是有格式的，如果可以使用复制功能，就可以创建一个通用的模版，每次都复制这个模版，然后进行修改。

![088fad17-1fdb-42fe-b235-84508fe6747c](https://user-images.githubusercontent.com/2356974/41332670-6ecb3bac-6f11-11e8-92f3-552b2b721b7f.png)

**Comment by Bosn** [comment]
已实现
