### ISSUE TITLE
点击测试后出现'Not Found'

### ISSUE THREAD

**Issue by elfgzp** [thx/rap2-dolores#64]
![image](https://user-images.githubusercontent.com/12834889/41419024-9c43dd24-7023-11e8-8823-d8f8dbb049e0.png)
![image](https://user-images.githubusercontent.com/12834889/41419036-a46b87b8-7023-11e8-90f3-6636340cbe28.png)

**Comment by hiql** [comment]
同问！

**Comment by Bosn** [comment]
React-router 的BUG，今日会修复。
