### ISSUE TITLE
仓库内模块和接口数量导致页面加载速度变慢的问题

### ISSUE THREAD

**Issue by kkroy-zs** [thx/rap2-dolores#66]
模块和接口数量一多就导致页面加载速度变得巨慢。
发现无论在编辑、取消接口修改，在切换接口、模块时，都会重新加载模块、接口的列表，导致变慢。

![rap2](https://user-images.githubusercontent.com/17328590/41972155-90e6a770-7a43-11e8-8d20-31020057b608.png)

**Comment by Bosn** [comment]
已加入了缓存，如果还是慢，可以考虑提升下服务器配置。

**Comment by Bosn** [comment]
后续我们也会关注慢查询，做优化。
