### ISSUE TITLE
mock接口跳转地址错误

### ISSUE THREAD

**Issue by yogkin** [thx/rap2-dolores#69]
<img width="729" alt="qq20180710-221131 2x" src="https://user-images.githubusercontent.com/13175725/42515379-3a019a32-848e-11e8-9c33-165a7a5db1f1.png">

点击后的链接如上图所示

**Comment by fengtaijun0507** [comment]
同问

**Comment by igit-cn** [comment]
同问！！！

**Comment by Bosn** [comment]
已修复
