### ISSUE TITLE
使用nginx代理，点击`插件`出现404，链接不对。

### ISSUE THREAD

**Issue by SamlenTsoi** [thx/rap2-dolores#70]
![image](https://user-images.githubusercontent.com/23205343/42623501-9a0e0f42-85f5-11e8-870a-27ed44cba042.png)

![image](https://user-images.githubusercontent.com/23205343/42623415-65f06548-85f5-11e8-97d4-cb84ec43ef49.png)

**Comment by Bosn** [comment]
react-router的bug，导致<Link组件to为绝对路径时生成错误的链接，该问题今天会修复。
