### ISSUE TITLE
为什么接口调用显示No match for

### ISSUE THREAD

**Issue by Glutton-CN** [thx/rap2-dolores#75]
本地搭建的rap2，前端、后端都配好了
建好仓库和接口，点击接口的地址
也就是访问`http://192.168.33.7:5000/repository/http://rap2api.taobao.org/app/mock/22248/u/verify`
页面上显示：
No match for `/repository/http://rap2api.taobao.org/app/mock/22248/u/verify`

**Comment by Bosn** [comment]
看下置顶帖子谢谢
