### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by jococi** [thx/rap2-dolores#95]
Wrote 39 CSS files to /www/rap2-dolores/src/
Creating an optimized production build...
Failed to compile.

./src/family/start.tsx
Cannot find module: '@material-ui/core/styles/MuiThemeProvider'. Make sure this package is installed.

You can install this package by running: npm install @material-ui/core/styles/MuiThemeProvider.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 build: `npm run lint && npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-14T03_32_13_197Z-debug.log

**Comment by ro1992613** [comment]
the same question

**Comment by bigfengyu** [comment]
是 material ui 升级发生 break change 导致，已经修复了。
